### PR TITLE
Fixed rank values

### PR DESCRIPTION
**Pull request by MihajloNesic**
I believe the rank for Jack, Queen and King should be 11, 12 and 13.

FYI, the tests for getting the values for Enums is completely unnecessary. It is an overkill.

### CODE REVIEW

**Comment by Daniel-Gill** [comment]
It's possible that the card values were assigned to the ones for [pontoon](https://en.wikipedia.org/wiki/Pontoon_(banking_game)#:~:text=The%20values%20of%20the%20cards%20are%20as%20follows%3A%20an%20Ace%20scores%201%20or%2011%20as%20desired%3B%20court%20cards%20score%2010%20each). Though, not very clear if so.

**Comment by MihajloNesic** [comment]
Maybe introduce a concept where a user can define the values of cards. Here the ace is the lowest, where in some games it is the highest (strongest) card

**Comment by lyudaio** [comment]
This is a problem I've been trying to solve for sometime. The ranks were the "default" value which is why Jack, Queen, and King were shown as a value of `10`. 

I was thinking of a hand calculation method to get total value of cards with an option to calculate custom values such as an Ace being 11 or 1 in the gameof BlackJack.

What do you think?

**Comment by MihajloNesic** [comment]
I think there should be default values and thus being able to give ranks their value, but maybe allow the user to define the values for each Rank when constructing a Deck.

I wouldn't mention any card game or pre-define the values for any game. Just let the user easily re-define the values and construct a Deck based on a game

**Comment by lyudaio** [comment]
Closing PR, I have reverted enum rank values to their original values as suggested. Thank you.

**Pull request closed without merging**
