### PR TITLE
Added split method in Deck

### PR DESCRIPTION
**Pull request by Daniel-Gill**
Hello, this is my first contribution to this project. I have added a single method in `Deck` which can split a deck into a specified number of `Hand`s.

### CODE REVIEW

**Comment by lyudaio** [comment]
> Hello, this is my first contribution to this project. I have added a single method in `Deck` which can split a deck into a specified number of `Hand`s.

Thanks for your contribution! We will likely include this in a future release. Before we merge into the main branch please remove the .gitignore. This file could change depending on who forks/clones the library and the scope of their packages.

**Comment by Daniel-Gill** [comment]
I have done as requested, though I would highly suggest that you maintain a .gitignore file to ensure that unwanted directories and files are not tracked.

**Comment by Narkoleptika** [comment]
f6add143e008d3ea36d6f151c66d222b8c1461d8 is a perfect example for why you should maintain a `.gitignore`

**Comment by lyudaio** [comment]
I'm including a .gitignore in next release along with this.

**Review by lyudaio — APPROVED** [review]
LGTM

**Pull request merged**
